# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    # - bash: echo Build FirstJob $(PipelineLevelVariable)
    # - bash: echo $(Build.BuildNumber)
    # - bash: echo $(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: echo java -version
    - bash: echo mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'System.DefaultWorkingDirectory'
        Contents: '**/*.yaml'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'       
    - bash: ls -R $(Build.ArtifactStagingDirectory)

#   - job: SecondJob
#     steps:
#     - bash: echo Build SecondJob $(PipelineLevelVariable)
# - stage: DevDeploy
#   dependsOn: Build
#   variables:
#     environment: Dev
#   jobs:
#   - job: DevDeployJob
#     steps:
#     - bash: echo $(environment)DeployJob
# - stage: QADeploy
#   dependsOn: Build
#   variables:
#     environment: QA
#   jobs:
#   - job: QADeployJob
#     steps:
#     - bash: echo $(environment)DeployJob
# - stage: ProdDeploy
#   dependsOn: 
#   - DevDeploy
#   - QADeploy
#   jobs:
#   - job: ProdDeployJob
#     steps:
#     - bash: echo ProdDeploy Job
